RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

VIA_ENABLE      = yes

LTO_ENABLE      = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball
MOUSEKEY_ENABLE = yes

OLED_ENABLE     = no
RGBLIGHT_ENABLE = no
